config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :posts

  resources :fthreads

  resources :forums

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  has_many :fthreads
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:parent_id, :name, :description, :ftype, :deleted, :can_post, :show_threads, :resolved_tag, :display_order, :open_time, :forum_moderators_only)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.text_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :ftype %><br>
    <%= f.text_field :ftype %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.text_field :deleted %>
  </div>
  <div class="field">
    <%= f.label :can_post %><br>
    <%= f.text_field :can_post %>
  </div>
  <div class="field">
    <%= f.label :show_threads %><br>
    <%= f.text_field :show_threads %>
  </div>
  <div class="field">
    <%= f.label :resolved_tag %><br>
    <%= f.text_field :resolved_tag %>
  </div>
  <div class="field">
    <%= f.label :display_order %><br>
    <%= f.text_field :display_order %>
  </div>
  <div class="field">
    <%= f.label :open_time %><br>
    <%= f.text_field :open_time %>
  </div>
  <div class="field">
    <%= f.label :forum_moderators_only %><br>
    <%= f.text_field :forum_moderators_only %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<h1>Listing forums</h1>

<table>
  <thead>
    <tr>
      <th>Parent</th>
      <th>Name</th>
      <th>Description</th>
      <th>Ftype</th>
      <th>Deleted</th>
      <th>Can post</th>
      <th>Show threads</th>
      <th>Resolved tag</th>
      <th>Display order</th>
      <th>Open time</th>
      <th>Forum moderators only</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forums.each do |forum| %>
      <tr>
        <td><%= forum.parent_id %></td>
        <td><%= forum.name %></td>
        <td><%= forum.description %></td>
        <td><%= forum.ftype %></td>
        <td><%= forum.deleted %></td>
        <td><%= forum.can_post %></td>
        <td><%= forum.show_threads %></td>
        <td><%= forum.resolved_tag %></td>
        <td><%= forum.display_order %></td>
        <td><%= forum.open_time %></td>
        <td><%= forum.forum_moderators_only %></td>
        <td><%= link_to 'Show', forum %></td>
        <td><%= link_to 'Edit', edit_forum_path(forum) %></td>
        <td><%= link_to 'Destroy', forum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum', new_forum_path %>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parent:</strong>
  <%= @forum.parent_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @forum.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @forum.description %>
</p>

<p>
  <strong>Ftype:</strong>
  <%= @forum.ftype %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @forum.deleted %>
</p>

<p>
  <strong>Can post:</strong>
  <%= @forum.can_post %>
</p>

<p>
  <strong>Show threads:</strong>
  <%= @forum.show_threads %>
</p>

<p>
  <strong>Resolved tag:</strong>
  <%= @forum.resolved_tag %>
</p>

<p>
  <strong>Display order:</strong>
  <%= @forum.display_order %>
</p>

<p>
  <strong>Open time:</strong>
  <%= @forum.open_time %>
</p>

<p>
  <strong>Forum moderators only:</strong>
  <%= @forum.forum_moderators_only %>
</p>

<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>