config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :posts

  resources :fthreads

  resources :forums

end

app/models/fthread.rb
class Fthread < ActiveRecord::Base
  belongs_to :forum
  has_many :posts
  has_many :comments
end

app/controllers/fthreads_controller.rb
class FthreadsController < ApplicationController
  before_action :set_fthread, only: [:show, :edit, :update, :destroy]

  # GET /fthreads
  # GET /fthreads.json
  def index
    @fthreads = Fthread.all
  end

  # GET /fthreads/1
  # GET /fthreads/1.json
  def show
  end

  # GET /fthreads/new
  def new
    @fthread = Fthread.new
  end

  # GET /fthreads/1/edit
  def edit
  end

  # POST /fthreads
  # POST /fthreads.json
  def create
    @fthread = Fthread.new(fthread_params)

    respond_to do |format|
      if @fthread.save
        format.html { redirect_to @fthread, notice: 'Fthread was successfully created.' }
        format.json { render :show, status: :created, location: @fthread }
      else
        format.html { render :new }
        format.json { render json: @fthread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fthreads/1
  # PATCH/PUT /fthreads/1.json
  def update
    respond_to do |format|
      if @fthread.update(fthread_params)
        format.html { redirect_to @fthread, notice: 'Fthread was successfully updated.' }
        format.json { render :show, status: :ok, location: @fthread }
      else
        format.html { render :edit }
        format.json { render json: @fthread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fthreads/1
  # DELETE /fthreads/1.json
  def destroy
    @fthread.destroy
    respond_to do |format|
      format.html { redirect_to fthreads_url, notice: 'Fthread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fthread
      @fthread = Fthread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fthread_params
      params.require(:fthread).permit(:user_id, :posted_time, :last_updated_time, :last_updated_user, :deleted, :is_spam, :stickied, :approved, :unresolved, :instructor_replied, :num_posts, :num_views, :votes, :locked, :anonymous, :title, :triage_sync_status, :triage_status, :private, :problem_id, :link, :_reporter_link, :_thread_can_be_resolved_without_triage, :_viewer_can_resolve_with_triage, :tags, :crumbs, :start_page, :num_pages, :_viewer_subscription, :_viewer_can_edit_title, :_viewer_can_resolve_without_triage, :_viewer_can_delete, :_viewer_can_toggle_private, :forum_id)
    end
end

app/helpers/fthreads_helper.rb
module FthreadsHelper
end

app/views/fthreads/_form.html.erb
<%= form_for(@fthread) do |f| %>
  <% if @fthread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fthread.errors.count, "error") %> prohibited this fthread from being saved:</h2>

      <ul>
      <% @fthread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :posted_time %><br>
    <%= f.text_field :posted_time %>
  </div>
  <div class="field">
    <%= f.label :last_updated_time %><br>
    <%= f.text_field :last_updated_time %>
  </div>
  <div class="field">
    <%= f.label :last_updated_user %><br>
    <%= f.text_field :last_updated_user %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.text_field :deleted %>
  </div>
  <div class="field">
    <%= f.label :is_spam %><br>
    <%= f.text_field :is_spam %>
  </div>
  <div class="field">
    <%= f.label :stickied %><br>
    <%= f.text_field :stickied %>
  </div>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.text_field :approved %>
  </div>
  <div class="field">
    <%= f.label :unresolved %><br>
    <%= f.text_field :unresolved %>
  </div>
  <div class="field">
    <%= f.label :instructor_replied %><br>
    <%= f.text_field :instructor_replied %>
  </div>
  <div class="field">
    <%= f.label :num_posts %><br>
    <%= f.text_field :num_posts %>
  </div>
  <div class="field">
    <%= f.label :num_views %><br>
    <%= f.text_field :num_views %>
  </div>
  <div class="field">
    <%= f.label :votes %><br>
    <%= f.text_field :votes %>
  </div>
  <div class="field">
    <%= f.label :locked %><br>
    <%= f.text_field :locked %>
  </div>
  <div class="field">
    <%= f.label :anonymous %><br>
    <%= f.text_field :anonymous %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :triage_sync_status %><br>
    <%= f.text_field :triage_sync_status %>
  </div>
  <div class="field">
    <%= f.label :triage_status %><br>
    <%= f.text_field :triage_status %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.text_field :private %>
  </div>
  <div class="field">
    <%= f.label :problem_id %><br>
    <%= f.text_field :problem_id %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :_reporter_link %><br>
    <%= f.text_field :_reporter_link %>
  </div>
  <div class="field">
    <%= f.label :_thread_can_be_resolved_without_triage %><br>
    <%= f.text_field :_thread_can_be_resolved_without_triage %>
  </div>
  <div class="field">
    <%= f.label :_viewer_can_resolve_with_triage %><br>
    <%= f.text_field :_viewer_can_resolve_with_triage %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :crumbs %><br>
    <%= f.text_field :crumbs %>
  </div>
  <div class="field">
    <%= f.label :start_page %><br>
    <%= f.text_field :start_page %>
  </div>
  <div class="field">
    <%= f.label :num_pages %><br>
    <%= f.text_field :num_pages %>
  </div>
  <div class="field">
    <%= f.label :_viewer_subscription %><br>
    <%= f.text_field :_viewer_subscription %>
  </div>
  <div class="field">
    <%= f.label :_viewer_can_edit_title %><br>
    <%= f.text_field :_viewer_can_edit_title %>
  </div>
  <div class="field">
    <%= f.label :_viewer_can_resolve_without_triage %><br>
    <%= f.text_field :_viewer_can_resolve_without_triage %>
  </div>
  <div class="field">
    <%= f.label :_viewer_can_delete %><br>
    <%= f.text_field :_viewer_can_delete %>
  </div>
  <div class="field">
    <%= f.label :_viewer_can_toggle_private %><br>
    <%= f.text_field :_viewer_can_toggle_private %>
  </div>
  <div class="field">
    <%= f.label :forum_id %><br>
    <%= f.text_field :forum_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fthreads/edit.html.erb
<h1>Editing fthread</h1>

<%= render 'form' %>

<%= link_to 'Show', @fthread %> |
<%= link_to 'Back', fthreads_path %>

app/views/fthreads/index.html.erb
<h1>Listing fthreads</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Posted time</th>
      <th>Last updated time</th>
      <th>Last updated user</th>
      <th>Deleted</th>
      <th>Is spam</th>
      <th>Stickied</th>
      <th>Approved</th>
      <th>Unresolved</th>
      <th>Instructor replied</th>
      <th>Num posts</th>
      <th>Num views</th>
      <th>Votes</th>
      <th>Locked</th>
      <th>Anonymous</th>
      <th>Title</th>
      <th>Triage sync status</th>
      <th>Triage status</th>
      <th>Private</th>
      <th>Problem</th>
      <th>Link</th>
      <th> reporter link</th>
      <th> thread can be resolved without triage</th>
      <th> viewer can resolve with triage</th>
      <th>Tags</th>
      <th>Crumbs</th>
      <th>Start page</th>
      <th>Num pages</th>
      <th> viewer subscription</th>
      <th> viewer can edit title</th>
      <th> viewer can resolve without triage</th>
      <th> viewer can delete</th>
      <th> viewer can toggle private</th>
      <th>Forum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fthreads.each do |fthread| %>
      <tr>
        <td><%= fthread.user_id %></td>
        <td><%= fthread.posted_time %></td>
        <td><%= fthread.last_updated_time %></td>
        <td><%= fthread.last_updated_user %></td>
        <td><%= fthread.deleted %></td>
        <td><%= fthread.is_spam %></td>
        <td><%= fthread.stickied %></td>
        <td><%= fthread.approved %></td>
        <td><%= fthread.unresolved %></td>
        <td><%= fthread.instructor_replied %></td>
        <td><%= fthread.num_posts %></td>
        <td><%= fthread.num_views %></td>
        <td><%= fthread.votes %></td>
        <td><%= fthread.locked %></td>
        <td><%= fthread.anonymous %></td>
        <td><%= fthread.title %></td>
        <td><%= fthread.triage_sync_status %></td>
        <td><%= fthread.triage_status %></td>
        <td><%= fthread.private %></td>
        <td><%= fthread.problem_id %></td>
        <td><%= fthread.link %></td>
        <td><%= fthread._reporter_link %></td>
        <td><%= fthread._thread_can_be_resolved_without_triage %></td>
        <td><%= fthread._viewer_can_resolve_with_triage %></td>
        <td><%= fthread.tags %></td>
        <td><%= fthread.crumbs %></td>
        <td><%= fthread.start_page %></td>
        <td><%= fthread.num_pages %></td>
        <td><%= fthread._viewer_subscription %></td>
        <td><%= fthread._viewer_can_edit_title %></td>
        <td><%= fthread._viewer_can_resolve_without_triage %></td>
        <td><%= fthread._viewer_can_delete %></td>
        <td><%= fthread._viewer_can_toggle_private %></td>
        <td><%= fthread.forum %></td>
        <td><%= link_to 'Show', fthread %></td>
        <td><%= link_to 'Edit', edit_fthread_path(fthread) %></td>
        <td><%= link_to 'Destroy', fthread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fthread', new_fthread_path %>

app/views/fthreads/new.html.erb
<h1>New fthread</h1>

<%= render 'form' %>

<%= link_to 'Back', fthreads_path %>

app/views/fthreads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @fthread.user_id %>
</p>

<p>
  <strong>Posted time:</strong>
  <%= @fthread.posted_time %>
</p>

<p>
  <strong>Last updated time:</strong>
  <%= @fthread.last_updated_time %>
</p>

<p>
  <strong>Last updated user:</strong>
  <%= @fthread.last_updated_user %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @fthread.deleted %>
</p>

<p>
  <strong>Is spam:</strong>
  <%= @fthread.is_spam %>
</p>

<p>
  <strong>Stickied:</strong>
  <%= @fthread.stickied %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @fthread.approved %>
</p>

<p>
  <strong>Unresolved:</strong>
  <%= @fthread.unresolved %>
</p>

<p>
  <strong>Instructor replied:</strong>
  <%= @fthread.instructor_replied %>
</p>

<p>
  <strong>Num posts:</strong>
  <%= @fthread.num_posts %>
</p>

<p>
  <strong>Num views:</strong>
  <%= @fthread.num_views %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @fthread.votes %>
</p>

<p>
  <strong>Locked:</strong>
  <%= @fthread.locked %>
</p>

<p>
  <strong>Anonymous:</strong>
  <%= @fthread.anonymous %>
</p>

<p>
  <strong>Title:</strong>
  <%= @fthread.title %>
</p>

<p>
  <strong>Triage sync status:</strong>
  <%= @fthread.triage_sync_status %>
</p>

<p>
  <strong>Triage status:</strong>
  <%= @fthread.triage_status %>
</p>

<p>
  <strong>Private:</strong>
  <%= @fthread.private %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @fthread.problem_id %>
</p>

<p>
  <strong>Link:</strong>
  <%= @fthread.link %>
</p>

<p>
  <strong> reporter link:</strong>
  <%= @fthread._reporter_link %>
</p>

<p>
  <strong> thread can be resolved without triage:</strong>
  <%= @fthread._thread_can_be_resolved_without_triage %>
</p>

<p>
  <strong> viewer can resolve with triage:</strong>
  <%= @fthread._viewer_can_resolve_with_triage %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @fthread.tags %>
</p>

<p>
  <strong>Crumbs:</strong>
  <%= @fthread.crumbs %>
</p>

<p>
  <strong>Start page:</strong>
  <%= @fthread.start_page %>
</p>

<p>
  <strong>Num pages:</strong>
  <%= @fthread.num_pages %>
</p>

<p>
  <strong> viewer subscription:</strong>
  <%= @fthread._viewer_subscription %>
</p>

<p>
  <strong> viewer can edit title:</strong>
  <%= @fthread._viewer_can_edit_title %>
</p>

<p>
  <strong> viewer can resolve without triage:</strong>
  <%= @fthread._viewer_can_resolve_without_triage %>
</p>

<p>
  <strong> viewer can delete:</strong>
  <%= @fthread._viewer_can_delete %>
</p>

<p>
  <strong> viewer can toggle private:</strong>
  <%= @fthread._viewer_can_toggle_private %>
</p>

<p>
  <strong>Forum:</strong>
  <%= @fthread.forum %>
</p>

<%= link_to 'Edit', edit_fthread_path(@fthread) %> |
<%= link_to 'Back', fthreads_path %>